<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pembayaran extends Model
{
    protected $table = 'pembayaran';
    protected $primaryKey = 'noPembayaran';

    protected $casts = [
        'noPembayaran' => 'string'
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }


    public function agen(){
        return $this->belongsTo('App\Agen', 'idAgen');
    }

    public function asuransi(){
        return $this->belongsTo('App\Asuransi', 'idAsuransi');
    }
}
